In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("data/CoilData.csv")

df

,coil,furnace Number,analyse,Hardness_1,Hardness_2,Width,Temperature before finishing mill,Temperature after finishing mill,Thickness,Thickness profile,...,p,s,al,ma,b,n,ti,cr,va,mo
0,396378,1,K371,10003,101,1302.1,1147,921,4.36,31,...,133,143,304,291,1,34,6,302,0,25
1,396376,3,K371,10123,101,1282.3,1150,920,4.37,35,...,118,90,395,384,1,33,12,189,25,7
2,396377,4,K321,10040,102,1297.4,1183,933,4.43,25,...,108,115,476,463,1,20,11,288,0,40
3,396379,3,K371,10243,102,1295.2,1165,910,4.44,28,...,139,98,306,296,1,21,9,253,0,9
4,396380,4,K321,10012,100,1293.3,1192,909,3.95,26,...,112,121,340,329,1,28,8,297,0,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57089,20814,1,K371,9781,98,1010.0,1193,883,1.84,20,...,53,129,303,296,1,30,8,238,1,27
57090,20815,3,K371,9799,98,1010.6,1176,900,1.84,19,...,59,127,315,308,1,32,8,236,1,25
57091,20816,1,K371,9864,99,1008.6,1187,909,1.84,17,...,80,120,355,347,1,37,9,230,0,21
57092,20817,3,K371,10039,100,1012.7,1161,893,1.84,21,...,108,129,306,296,1,27,7,280,0,25
57093,20818,1,K371,9841,98,1008.7,1196,913,1.84,16,...,73,113,357,347,1,34,8,223,0,19